version: '3'

services:
  app:
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    container_name: dotnetcoreapp
    tty: true
    ports:
      - 10080:80
    volumes:
      - ./src:/src
    working_dir: "/src"